language: python
python:
  - 3.3
  - 3.4
  - 3.5

sudo: false

before_install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda config --add channels https://conda.anaconda.org/faph
  - conda update -q conda
  - conda info -a
  - conda create -q -n pyenv python=$TRAVIS_PYTHON_VERSION nose coverage appdirs
  - source activate pyenv

install:
  - python setup.py install

script:
  - nosetests --with-coverage --cover-package=mru

after_success:
  - pip install coveralls
  - coveralls
