package: mru
build_targets: conda

platform:
  - linux-64

engine:
  - python=3.3
  - python=3.4
  - python=3.5

before_script:
  - conda update --name=root conda conda-build

script:
  - conda build .